### PR TITLE
Makes the module work in 0.8.6 and adds support for webm tokens

### LINKED ISSUE #5: Enhancement: Using webm files
Being able to use webm files instead of static images would be a great addition now that animated tokens are starting to show everywhere

### LINKED ISSUE #11: 0.8.x Compatibility
This module does not appear to work in 0.8.

### PR DESCRIPTION
**Pull request by johnnolan**
Hi, hope you don't mind but I wanted to get this working for 0.8.6 for my game.

The PR enables webm tokens and also updates how the data from the hooks is parsed to work in 0.8.6

Feel free to ignore and close this PR if you are already working on it or steal bits out for your own version, just wanted to share in case it helped.

Thanks
John
Discord: JB#2780

Fixes #5 
Fixes #11

### CODE REVIEW

**Comment by rnarducci** [comment]
Hey, I was wondering how I would use your branch in my game as well? What link would I need to use, as it's not really liking the ones I've tried.

**Comment by johnnolan** [comment]
> 
> 
> Hey, I was wondering how I would use your branch in my game as well? What link would I need to use, as it's not really liking the ones I've tried.

Hey, you could probably install the module then overwrite the file in WeaponsDrawn.js with this file https://raw.githubusercontent.com/VanirDev/WeaponsDrawn/53db79877543cb54dad428db67837add85420bd0/dist/WeaponsDrawn.js but you would need access to the files via an ftp client if it is hosted on a server somewhere.

**Comment by rnarducci** [comment]
> 
> 
> > Hey, I was wondering how I would use your branch in my game as well? What link would I need to use, as it's not really liking the ones I've tried.
> 
> Hey, you could probably install the module then overwrite the file in WeaponsDrawn.js with this file https://raw.githubusercontent.com/VanirDev/WeaponsDrawn/53db79877543cb54dad428db67837add85420bd0/dist/WeaponsDrawn.js but you would need access to the files via an ftp client if it is hosted on a server somewhere.

Got it working, much appreciated!

**Comment by GambetTV** [comment]
This was working until I upgraded to 0.8.8, and now it only works perfectly if I add tokens to combat mode one at a time. If I group them up and add them all at once, they will not revert to their original tokens when I pull them out of combat mode. The only way to fix it is to hit F5 and refresh.

**Comment by johnnolan** [comment]
> 
> 
> This was working until I upgraded to 0.8.8, and now it only works perfectly if I add tokens to combat mode one at a time. If I group them up and add them all at once, they will not revert to their original tokens when I pull them out of combat mode. The only way to fix it is to hit F5 and refresh.

Just put an update in to try, hopefully works until VanirDev puts a update out. You may need to setup your token images again fyi for it to work.

**Pull request closed without merging**
